// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void test2() {
    driver.get("https://www.rmf24.pl/");
    driver.manage().window().setSize(new Dimension(997, 820));
    driver.findElement(By.cssSelector(".icons")).click();
    driver.findElement(By.cssSelector(".menuToggle")).click();
    driver.findElement(By.cssSelector(".icons")).click();
    driver.findElement(By.cssSelector(".menu-button")).click();
    driver.findElement(By.cssSelector(".hidden-xs > .sluchajR")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".listRadioS > li:nth-child(2) .wlaczR")).click();
    vars.put("win7721", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7721").toString());
    js.executeScript("window.scrollTo(0,800)");
    driver.switchTo().frame(1);
    driver.findElement(By.id("wyszukaj")).click();
    driver.findElement(By.id("wyszukaj")).sendKeys("24");
    driver.findElement(By.cssSelector(".szukajB > .material-icons")).click();
    driver.findElement(By.cssSelector(".day-past:nth-child(20) a > .day")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".title-28930"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("#next > span")).click();
    driver.findElement(By.cssSelector(".szukajB > .material-icons")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("listaCont"));
      assert(elements.size() > 0);
    }
  }
}
