// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void test1() {
    driver.get("https://www.rmf24.pl/");
    driver.manage().window().setSize(new Dimension(997, 820));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.id("gr-btn-agree")).click();
    vars.put("win7448", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win7448").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".isBigPhotoMain .playMixerIcon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".menuToggle")).click();
    driver.findElement(By.cssSelector(".menu-button")).click();
    driver.findElement(By.cssSelector(".arrow-1")).click();
    driver.findElement(By.cssSelector(".col-xs-12 > .mainStart-poznan")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col-md-6 .img-responsive"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,600)");
    driver.findElement(By.linkText("Piękna opalenizna bez plam i smug – jaki balsam brązujący wybrać dla bladej skóry?")).click();
    driver.findElement(By.cssSelector(".i2:nth-child(1) > span")).click();
    js.executeScript("window.scrollTo(0,6)");
    js.executeScript("window.scrollTo(0,800)");
    driver.findElement(By.linkText("Gigantyczne korki na zakopiance. Gdzie kierowcy postoją najdłużej?")).click();
    driver.findElement(By.cssSelector(".menuToggle")).click();
    driver.findElement(By.cssSelector(".menuToggle")).click();
    js.executeScript("window.scrollTo(0,500)");
  }
}
